name: release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install nim
        run: |
          sudo apt update
          sudo apt install nim -y
          nim --version

      - name: compile
        run: nim c --out:forge -d:release src/forge.nim

      - name: package-artifact
        run: |
          ls -R .
          mkdir release
          cp forge release/
          tar czvf forge-${{ github.ref_name }}.tar.gz -C release .

      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: forge-${{ github.ref_name }}.tar.gz
          tag: ${{ github.ref_name }}
